<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Hồ sơ doanh nghiệp thành viên CLB Doanh nhân Họ Lê Đắk Lắk."><title id="pageTitle">Hồ sơ doanh nghiệp · LĐBC</title><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=Be+Vietnam+Pro:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/member-landing.css?v=6"></head>
<body><nav class="member-nav"><a class="member-brand" href="/">Lê <span>DOANH NHÂN HỌ LÊ<br><small>ĐẮK LẮK</small></span></a><a class="back-link" href="/index.html#thanhVien">← Danh sách doanh nghiệp</a></nav><main>
<section class="member-hero"><div class="portrait-panel"><div id="banner" class="member-portrait" aria-label="Logo doanh nghiệp"></div><span class="portrait-caption">HỒ SƠ DOANH NGHIỆP</span></div><div class="member-intro"><p class="eyebrow">CỘNG ĐỒNG DOANH NHÂN HỌ LÊ</p><span id="tag" class="member-role"></span><h1 id="title">Đang tải hồ sơ…</h1><p id="excerpt" class="member-bio"></p><div id="actions" class="member-actions"></div><a id="ownerLink" class="text-link" hidden></a><span id="date" hidden></span></div></section>
<section class="member-businesses"><div class="section-heading"><div><p class="eyebrow">THÔNG TIN</p><h2>Thông tin liên hệ</h2></div></div><article class="landing-business"><div id="infoCard" class="business-info-grid"></div></article></section>
<section class="member-businesses"><div class="section-heading"><div><p class="eyebrow">GIỚI THIỆU</p><h2>Giới thiệu doanh nghiệp</h2></div></div><article class="landing-business"><div id="content" class="business-body" aria-live="polite"></div></article></section>
<section class="member-businesses" id="gallerySection" hidden><div class="section-heading"><div><p class="eyebrow">HÌNH ẢNH</p><h2>Thư viện hình ảnh</h2></div></div><div id="gallery" class="gallery-grid"></div></section>
</main><footer><span>CLB Doanh nhân Họ Lê Đắk Lắk</span><a href="/index.html#join">Kết nối cùng cộng đồng ↗</a></footer>
<script src="/stc-config.js?v=6"></script><script src="/assets/cms-common.js?v=6"></script><script src="/assets/public-cms.js?v=6"></script></body></html>
