-- Bổ sung nội dung gốc, không ghi đè nội dung đã sửa.
begin;
insert into public.ldbc_site_content(id,value) values
('hero-title','Câu Lạc Bộ
Doanh Nhân Họ Lê
Đắk Lắk'),
('hero-motto','"Đoàn kết · Phát triển · Rạng danh Lê tộc Việt Nam"'),
('hero-intro','Nơi kết nối, chia sẻ và cùng nhau phát triển của những doanh nhân mang dòng họ Lê trên mảnh đất Tây Nguyên hùng vĩ.'),
('about-title','Đoàn kết dòng họ —
Kiến tạo tương lai'),
('about-quote','"Với tinh thần Tự hào truyền thống, kiến tạo tương lai và Bản lĩnh vững vàng, vươn tới thịnh vượng, chúng tôi cùng nhau xây dựng mạng lưới kinh doanh Họ Lê vững mạnh trên đất Tây Nguyên."'),
('about-intro','Câu lạc bộ Doanh nhân Họ Lê Đắk Lắk là thành viên của CLB Doanh nhân Họ Lê Việt Nam — tổ chức trực thuộc Hội đồng Họ Lê Việt Nam. Chúng tôi hoạt động theo tinh thần tương thân tương ái, cùng nhau phát triển kinh doanh và gìn giữ truyền thống dòng tộc.'),
('join-title','Trở Thành Thành Viên
Câu Lạc Bộ Họ Lê Đắk Lắk'),
('join-intro','Cùng chúng tôi xây dựng mạng lưới doanh nhân Họ Lê vững mạnh — nơi mỗi thành viên được kết nối, hỗ trợ và cùng nhau phát triển dưới tinh thần "Đoàn kết – Phát triển – Rạng danh Lê tộc Việt Nam".'),
('contact','Địa chỉ: 321 Y Wang, P. Ea Kao, T.Đắk Lắk
Email: clbdoanhnanhhole.daklak@gmail.com
Điện thoại: 0945 820 779 (Chủ tịch Lê Văn Vương)'),
('ticker','Đại hội CLB Doanh nhân Họ Lê Việt Nam lần I: 300 đại biểu, bầu 46 ủy viên BCH, Chủ tịch TS. Lê Xuân Thảo | 
CLB Doanh nhân Họ Lê Đắk Lắk kết nối với mạng lưới doanh nhân Họ Lê toàn quốc | 
Chương trình Khuyến học – Khuyến tài năm 2025: Trao 50 suất học bổng | 
Hội nghị giao thương doanh nghiệp Họ Lê Tây Nguyên sắp diễn ra tại Buôn Ma Thuột'),
('page-11','Lê CLB Doanh Nhân Họ Lê Đắk Lắk'),
('page-12','#hero'),
('page-13','Giới thiệu'),
('page-14','#gioithieu'),
('page-15','Ban lãnh đạo'),
('page-16','#lanhDao'),
('page-17','Hoạt động'),
('page-18','#hoatDong'),
('page-19','Khuyến học'),
('page-20','#khuyenHoc'),
('page-21','Cội nguồn'),
('page-22','#coiNguon'),
('page-23','Thành viên'),
('page-24','#thanhVien'),
('page-25','Tham gia'),
('page-26','#join'),
('page-27','Xem chi tiết'),
('page-28','https://holevietnam.vn/dai-hoi-dai-bieu-clb-doanh-nhan-ho-le-viet-nam-lan-thu-i-thanh-cong-tot-dep/'),
('page-29','TIN MỚI'),
('page-30','Thành lập tại Đắk Lắk · Trực thuộc CLB DN Họ Lê Việt Nam'),
('page-31','Tham gia CLB'),
('page-32','#join'),
('page-33','Tìm hiểu thêm'),
('page-34','#gioithieu'),
('page-35','120+'),
('page-36','Thành viên'),
('page-37','5+'),
('page-38','Năm hoạt động'),
('page-39','30+'),
('page-40','Doanh nghiệp'),
('page-41','15+'),
('page-42','Sự kiện / năm'),
('page-43','https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=800&q=80'),
('page-44','Về chúng tôi'),
('page-45','— Ban Chủ nhiệm CLB Doanh nhân Họ Lê Đắk Lắk'),
('page-46','🤝 Kết nối giao thương'),
('page-47','Xây dựng mạng lưới hợp tác kinh doanh giữa các thành viên trong và ngoài tỉnh.'),
('page-48','📈 Phát triển kinh tế'),
('page-49','Chia sẻ kinh nghiệm, hỗ trợ khởi nghiệp và mở rộng quy mô doanh nghiệp.'),
('page-50','🎋 Tri ân tiên tổ'),
('page-51','Gìn giữ đạo lý "uống nước nhớ nguồn", kết nối về Lam Kinh đất tổ nhà Lê.'),
('page-52','🌱 Tương thân tương ái'),
('page-53','Hỗ trợ thành viên khó khăn, đóng góp cho cộng đồng và xã hội Đắk Lắk.'),
('page-54','Lê'),
('page-55','Trực thuộc Hội đồng Họ Lê Việt Nam'),
('page-56','CLB Doanh nhân Họ Lê Đắk Lắk là thành viên chính thức của CLB Doanh nhân Họ Lê Việt Nam — tổ chức với hơn 300 doanh nhân tiêu biểu từ khắp mọi miền đất nước. Đại hội lần thứ I (10/2025) đã bầu BCH 46 thành viên, Chủ tịch là TS. Lê Xuân Thảo — Phó Chủ tịch thường trực Hội đồng Họ Lê Việt Nam.'),
('page-57','Truy cập Hội đồng Họ Lê Việt Nam →'),
('page-58','https://holevietnam.vn'),
('page-59','Ban điều hành'),
('page-60','Những Người Dẫn Dắt'),
('page-61','Đội ngũ lãnh đạo tâm huyết, kiến tạo và phát triển cộng đồng doanh nhân Họ Lê tại Đắk Lắk.'),
('page-62',''),
('page-63','VV'),
('page-64','Lê Văn Vương'),
('page-65','Chủ tịch'),
('page-66','Chủ tịch CLB Doanh nhân Họ Lê Đắk Lắk, người dẫn dắt và đại diện cho cộng đồng doanh nhân dòng họ Lê trên địa bàn tỉnh.'),
('page-67','📞 0945 820 779'),
('page-68','tel:0945820779'),
('page-69',''),
('page-70','QH'),
('page-71','Lê Quốc Hùng'),
('page-72','Phó Chủ tịch'),
('page-73','Phó Chủ tịch CLB, hỗ trợ điều hành và thúc đẩy các hoạt động kết nối kinh doanh của doanh nhân Họ Lê.'),
('page-74','📞 0886 575 868'),
('page-75','tel:0886575868'),
('page-76',''),
('page-77','TQ'),
('page-78','Lê Thị Quỳnh'),
('page-79','Phó Chủ tịch'),
('page-80','Phó Chủ tịch CLB, phụ trách các hoạt động phát triển thành viên và chương trình khuyến học – khuyến tài.'),
('page-81','📞 0906 515 888'),
('page-82','tel:0906515888'),
('page-83',''),
('page-84','TD'),
('page-85','Lê Tấn Dũng'),
('page-86','Phó Chủ tịch'),
('page-87','Phó Chủ tịch CLB, phụ trách kết nối giao thương và mở rộng quan hệ hợp tác với các tỉnh thành trong cả nước.'),
('page-88','📞 0889 334 747'),
('page-89','tel:0889334747'),
('page-90',''),
('page-91','QT'),
('page-92','Lê Quang Toàn'),
('page-93','Chánh Văn phòng'),
('page-94','Điều phối hoạt động văn phòng CLB, quản lý hành chính và tổ chức các sự kiện của câu lạc bộ.'),
('page-95','📞 0823 047 047'),
('page-96','tel:0823047047'),
('page-97',''),
('page-98','LL'),
('page-99','Lê Long'),
('page-100','Ủy viên BCH'),
('page-101','Ủy viên Ban Chấp hành, tham gia hoạch định chiến lược và triển khai các hoạt động của CLB.'),
('page-102','📞 0984 553 246'),
('page-103','tel:0984553246'),
('page-104',''),
('page-105','VK'),
('page-106','Lê Văn Khâm'),
('page-107','Ủy viên BCH'),
('page-108','Ủy viên Ban Chấp hành, đóng góp vào các hoạt động phát triển tổ chức và tương thân tương ái của CLB.'),
('page-109','📞 0379 786 574'),
('page-110','tel:0379786574'),
('page-111','Tin tức & Sự kiện'),
('page-112','Hoạt Động Nổi Bật'),
('page-113','Cập nhật những tin tức mới nhất về hoạt động của CLB Doanh nhân Họ Lê Đắk Lắk và tổ chức Họ Lê toàn quốc.'),
('page-114','Khuyến học · Khuyến tài'),
('page-115','Đầu Tư Cho Thế Hệ Tương Lai'),
('page-116','CLB thực hiện phong trào khuyến học – khuyến tài theo tinh thần của Hội đồng Họ Lê Việt Nam: đẩy mạnh học tập suốt đời, vinh danh nhân tài, hỗ trợ học sinh, sinh viên Họ Lê vươn lên.'),
('page-117','Ủng hộ quỹ học bổng'),
('page-118','#join'),
('page-119','50+'),
('page-120','Suất học bổng đã trao'),
('page-121','200+'),
('page-122','Triệu đồng quỹ học bổng'),
('page-123','5'),
('page-124','Năm triển khai liên tục'),
('page-125','100%'),
('page-126','Học sinh nhận đều đậu ĐH'),
('page-127','Tìm về cội nguồn'),
('page-128','Dòng Họ Lê — Lịch Sử Vẻ Vang'),
('page-129','Dòng họ Lê Việt Nam gắn liền với trang sử hào hùng của dân tộc. Cùng nhau tìm hiểu và gìn giữ truyền thống dòng tộc ngàn năm.'),
('page-130','🏯'),
('page-131','Lam Kinh — Đất Tổ Nhà Lê'),
('page-132','Khu di tích quốc gia đặc biệt Lam Kinh (Thanh Hoá) — nơi phát tích của nhà Lê, nơi Đức Vua Lê Thái Tổ khởi nghĩa Lam Sơn đánh đuổi giặc Minh.'),
('page-133','Tìm hiểu thêm →'),
('page-134','https://holevietnam.vn/danh-muc/video/lam-kinh-dat-to-nha-le/'),
('page-135','📜'),
('page-136','Gia Phả Dòng Họ'),
('page-137','Lưu giữ và kết nối gia phả các chi nhánh Họ Lê tại Đắk Lắk, kết nối về nguồn cội với Hội đồng Họ Lê Việt Nam.'),
('page-138','Kết nối gia phả →'),
('page-139','https://holevietnam.vn/chuyen-muc/tim-ve-coi-nguon/gia-pha-dong-ho/'),
('page-140','🔗'),
('page-141','Kết Nối Dòng Họ'),
('page-142','Kết nối với Họ Lê tại các tỉnh thành, cùng sinh hoạt trong mạng lưới Hội đồng Họ Lê toàn quốc và quốc tế.'),
('page-143','Kết nối ngay →'),
('page-144','https://holevietnam.vn/chuyen-muc/tim-ve-coi-nguon/ket-noi-dong-ho/'),
('page-145','Tự hào truyền thống'),
('page-146','Danh Nhân Họ Lê Tiêu Biểu'),
('page-147','Những người con ưu tú của dòng họ Lê đã để lại dấu ấn trong lịch sử và văn hoá Việt Nam.'),
('page-148','👑'),
('page-149','Vua Lê Thái Tổ'),
('page-150','Người khởi nghĩa Lam Sơn, đánh đuổi giặc Minh, lập nên nhà Lê — triều đại huy hoàng nhất lịch sử Việt Nam.'),
('page-151','🏛️'),
('page-152','Vua Lê Thánh Tông'),
('page-153','Vị vua anh minh, thi nhân lỗi lạc, xây dựng Đại Việt thịnh trị, mở mang bờ cõi về phương Nam.'),
('page-154','⚕️'),
('page-155','Hải Thượng Lãn Ông Lê Hữu Trác'),
('page-156','Đại danh y của dân tộc, người đặt nền tảng cho y học cổ truyền Việt Nam, ảnh hưởng mang tầm quốc tế.'),
('page-157','🌟'),
('page-158','Doanh Nhân Họ Lê Thời Hiện Đại'),
('page-159','Thế hệ doanh nhân Họ Lê hôm nay tiếp nối truyền thống, kiến tạo tương lai và rạng danh dòng tộc.'),
('page-160','Cộng đồng'),
('page-161','Thành Viên Tiêu Biểu'),
('page-162','Hơn 120 doanh nhân mang Họ Lê đang hoạt động trong nhiều lĩnh vực tại Đắk Lắk.'),
('page-163','👥'),
('page-164','Danh sách thành viên đang được cập nhật'),
('page-165','CLB có hơn 120 thành viên là doanh nhân Họ Lê đang hoạt động tại Đắk Lắk. Danh sách đầy đủ sẽ được công bố sớm sau khi hoàn tất đăng ký chính thức.'),
('page-166','Đăng ký tham gia CLB →'),
('page-167','#join'),
('page-168','📞 Liên hệ đăng ký: 0823 047 047'),
('page-169','tel:0823047047'),
('page-170','Lê Quang Toàn — Chánh Văn phòng'),
('page-171','CLB Doanh Nhân Họ Lê Đắk Lắk'),
('page-172','"Đoàn kết · Phát triển · Rạng danh Lê tộc Việt Nam"'),
('page-173','Điều hướng'),
('page-174','Giới thiệu CLB'),
('page-175','#gioithieu'),
('page-176','Ban lãnh đạo'),
('page-177','#lanhDao'),
('page-178','Tin tức & Sự kiện'),
('page-179','#hoatDong'),
('page-180','Khuyến học – Khuyến tài'),
('page-181','#khuyenHoc'),
('page-182','Tìm về cội nguồn'),
('page-183','#coiNguon'),
('page-184','Thành viên'),
('page-185','#thanhVien'),
('page-186','Tổ chức quốc gia'),
('page-187','Hội đồng Họ Lê Việt Nam'),
('page-188','https://holevietnam.vn'),
('page-189','CLB DN Họ Lê Việt Nam'),
('page-190','https://holevietnam.vn/chuyen-muc/clb-doanh-nhan-ho-le-2/'),
('page-191','Truyền thống dòng họ'),
('page-192','https://holevietnam.vn/truyen-thong-dong-ho/'),
('page-193','Lam Kinh – Đất tổ nhà Lê'),
('page-194','https://holevietnam.vn/danh-muc/video/lam-kinh-dat-to-nha-le/'),
('page-195','Kết nối'),
('page-196','Facebook CLB'),
('page-197','#'),
('page-198','Nhóm Zalo'),
('page-199','#'),
('page-200','Điều lệ CLB'),
('page-201','#'),
('page-202','Quy ước hoạt động'),
('page-203','#'),
('page-204','Liên hệ & Đăng ký'),
('page-205','#join'),
('page-206','© 2025 CLB Doanh Nhân Họ Lê Đắk Lắk · Trực thuộc Hội đồng Họ Lê Việt Nam'),
('page-207','Đoàn kết · Uy tín · Phát triển'),
('page-208','×')
on conflict(id) do nothing;
commit;
