-- Import existing public content only; existing edited records are preserved.
BEGIN;
insert into public.ldbc_posts (slug,title,category,excerpt,body,cover_url,status,published_at) values ('giao-luu-ca-phe','GẶp gỡ, sẻ chia – CLB Doanh Nhân Họ Lê Đắk Lắk tổ chức buổi giao lưu cà phê đầu tuần','Kết nối · Giao thương','Ngày 06/9/2026, tại văn phòng CLB Doanh Nhân Họ Lê Đắk Lắk đã diễn ra một buổi giao lưu cà phê thân mật, với sự tham dự của Chủ tịch Lê Văn Vương cùng hai thành viên: anh Lê Khâm và anh Lê Quang Toàn.','[{"type":"p","text":"Ngày 06/9/2026, tại văn phòng CLB Doanh Nhân Họ Lê Đắk Lắk đã diễn ra một buổi giao lưu cà phê thân mật, với sự tham dự của Chủ tịch Lê Văn Vương cùng hai thành viên: anh Lê Khâm và anh Lê Quang Toàn."},{"type":"p","text":"Đây là hoạt động gặp gỡ định kỳ nằm trong chuỗi sinh hoạt kết nối hội viên của CLB, nhằm tạo không gian để các thành viên cùng trao đổi, chia sẻ kinh nghiệm và gắn kết tình cảm trong cộng đồng doanh nhân Họ Lê tại Đắk Lắk."},{"type":"img","src":"/anh-giao-luu-1.jpg","caption":"Chủ tịch Lê Văn Vương cùng anh Lê Khâm và anh Lê Quang Toàn tại buổi giao lưu"},{"type":"h2","text":"CHIA Sẻ VỀ CỘI NGUỒN, TIếP NỐI TRUYỀN THỐNG"},{"type":"p","text":"Mở đầu buổi gặp, Chủ tịch Lê Văn Vương đã dành thời gian ôn lại dòng lịch sử và những giá trị cội nguồn của dòng họ Lê. Anh nhấn mạnh, việc gìn giữ và tiếp nối truyền thống không chỉ là trách nhiệm của mỗi cá nhân với gia tộc, mà còn là nền tảng tinh thần để cộng đồng doanh nhân Họ Lê tại Đắk Lắk thêm gắn bó, đoàn kết trong hoạt động kinh doanh cũng như các hoạt động xã hội."},{"type":"h2","text":"ĐỊNH HƯỚNG, GÓP Ý PHÁT TRIỂN DOANH NGHIỆP CHO TỪNG THÀNH VIÊN"},{"type":"p","text":"Tại buổi giao lưu, Chủ tịch Lê Văn Vương cũng đã trực tiếp trao đổi, góp ý và định hướng phát triển doanh nghiệp cho từng thành viên tham dự. Bằng kinh nghiệm thực tiễn trong hoạt động kinh doanh, anh đã đưa ra những nhận xét cụ thể, gợi mở hướng đi phù hợp với đặc thù của từng đơn vị, được các thành viên đánh giá cao và ghi nhận."},{"type":"h2","text":"KHÉP LẠI BẰNG NHỮNG MÓN QUÀ Ý NGHĨA"},{"type":"p","text":"Buổi giao lưu khép lại trong không khí ấm áp, nghĩa tình. Chủ tịch Lê Văn Vương đã trao tặng các thành viên tham dự trà hoa và trà cascara. Đáp lại, anh Lê Khâm cũng gửi tặng Chủ tịch Lê Văn Vương món quà Trung thu sớm, thay lời chúc mừng một mùa đoàn viên ấm áp sắp tới."},{"type":"img","src":"/anh-giao-luu-2.jpg","caption":"Lê Khâm tặng quà Trung thu đến Chủ tịch Lê Văn Vương"},{"type":"p","text":"Những buổi giao lưu như thế này tiếp tục khẳng định tinh thần gắn kết, sẻ chia của CLB Doanh Nhân Họ Lê Đắk Lắk – nơi không chỉ kết nối kinh doanh mà còn vun đắp tình thân trong cộng đồng dòng họ."}]'::jsonb,'','published','2026-09-06T00:00:00+07:00') on conflict (slug) do nothing;
insert into public.ldbc_posts (slug,title,category,excerpt,body,cover_url,status,published_at) values ('dai-hoi-clb-vn-i','Đại hội CLB Doanh nhân Họ Lê Việt Nam lần thứ I — 300 đại biểu tại Hải Tiến, Thanh Hoá','Sự kiện quốc gia','CLB Doanh nhân Họ Lê Đắk Lắk cử đoàn đại biểu tham dự Đại hội lần thứ I, nhiệm kỳ 2024-2030. Đại hội đã bầu 46 ủy viên BCH; TS. Lê Xuân Thảo đắc cử Chủ tịch CLB toàn quốc. Phái đoàn Đắk Lắk trình bày sáng kiến kết nối doanh nghiệp Tây Nguyên.','[{"type":"p","text":"CLB Doanh nhân Họ Lê Đắk Lắk cử đoàn đại biểu tham dự Đại hội lần thứ I, nhiệm kỳ 2024-2030. Đại hội đã bầu 46 ủy viên BCH; TS. Lê Xuân Thảo đắc cử Chủ tịch CLB toàn quốc. Phái đoàn Đắk Lắk trình bày sáng kiến kết nối doanh nghiệp Tây Nguyên."}]'::jsonb,'','published','2025-10-12T00:00:00+07:00') on conflict (slug) do nothing;
insert into public.ldbc_posts (slug,title,category,excerpt,body,cover_url,status,published_at) values ('le-dang-huong-lam-kinh','Hành trình về nguồn — Lễ dâng hương tại Lam Kinh, Thanh Hoá','Tri ân tiên tổ','Đoàn doanh nhân Họ Lê Đắk Lắk cùng đoàn dâng hương tưởng niệm Đức Vua Lê Thái Tổ tại Khu di tích đặc biệt Lam Kinh.','[{"type":"p","text":"Đoàn doanh nhân Họ Lê Đắk Lắk cùng đoàn dâng hương tưởng niệm Đức Vua Lê Thái Tổ tại Khu di tích đặc biệt Lam Kinh."}]'::jsonb,'','published','2025-10-11T00:00:00+07:00') on conflict (slug) do nothing;
insert into public.ldbc_posts (slug,title,category,excerpt,body,cover_url,status,published_at) values ('hoc-bong-2024','Trao 50 suất học bổng "Họ Lê Tiếp Sức" cho học sinh xuất sắc Đắk Lắk','Khuyến học','CLB phối hợp Ban Khuyến học trao tặng học bổng, góp phần đầu tư cho thế hệ tương lai dòng họ.','[{"type":"p","text":"CLB phối hợp Ban Khuyến học trao tặng học bổng, góp phần đầu tư cho thế hệ tương lai dòng họ."}]'::jsonb,'','published','2024-10-20T00:00:00+07:00') on conflict (slug) do nothing;
insert into public.ldbc_site_content (id,value) values ('hero-title','Câu Lạc Bộ
Doanh Nhân Họ Lê
Đắk Lắk') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('hero-motto','"Đoàn kết · Phát triển · Rạng danh Lê tộc Việt Nam"') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('hero-intro','Nơi kết nối, chia sẻ và cùng nhau phát triển của những doanh nhân mang dòng họ Lê trên mảnh đất Tây Nguyên hùng vĩ.') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('about-title','Đoàn kết dòng họ —
Kiến tạo tương lai') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('about-quote','"Với tinh thần Tự hào truyền thống, kiến tạo tương lai và Bản lĩnh vững vàng, vươn tới thịnh vượng, chúng tôi cùng nhau xây dựng mạng lưới kinh doanh Họ Lê vững mạnh trên đất Tây Nguyên."') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('about-intro','Câu lạc bộ Doanh nhân Họ Lê Đắk Lắk là thành viên của CLB Doanh nhân Họ Lê Việt Nam — tổ chức trực thuộc Hội đồng Họ Lê Việt Nam. Chúng tôi hoạt động theo tinh thần tương thân tương ái, cùng nhau phát triển kinh doanh và gìn giữ truyền thống dòng tộc.') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('join-title','Trở Thành Thành Viên
Câu Lạc Bộ Họ Lê Đắk Lắk') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('join-intro','Cùng chúng tôi xây dựng mạng lưới doanh nhân Họ Lê vững mạnh — nơi mỗi thành viên được kết nối, hỗ trợ và cùng nhau phát triển dưới tinh thần "Đoàn kết – Phát triển – Rạng danh Lê tộc Việt Nam".') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('contact','Địa chỉ: 321 Y Wang, P. Ea Kao, T.Đắk Lắk
Email: clbdoanhnanhhole.daklak@gmail.com
Điện thoại: 0945 820 779 (Chủ tịch Lê Văn Vương)') on conflict (id) do nothing;
insert into public.ldbc_site_content (id,value) values ('ticker','Đại hội CLB Doanh nhân Họ Lê Việt Nam lần I: 300 đại biểu, bầu 46 ủy viên BCH, Chủ tịch TS. Lê Xuân Thảo | 
CLB Doanh nhân Họ Lê Đắk Lắk kết nối với mạng lưới doanh nhân Họ Lê toàn quốc | 
Chương trình Khuyến học – Khuyến tài năm 2025: Trao 50 suất học bổng | 
Hội nghị giao thương doanh nghiệp Họ Lê Tây Nguyên sắp diễn ra tại Buôn Ma Thuột') on conflict (id) do nothing;
COMMIT;
