'use strict';
const $=id=>document.getElementById(id);
let collection='posts',memberCatalog=[],selectedMember=null;
const MEMBER_CATEGORY='Doanh nghiệp thành viên';
let posts=[],content=[],fields=[],current=null,dirty=false,busy=false,cover='',blocks=[],contentDirty=new Set(),activeView='posts';
function tell(message,error=false){$('message').textContent=message;$('message').classList.toggle('error',error)}
async function api(action,body){
  const r=await fetch(window.STC_CONFIG.API_BASE+'?action='+action,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(60000)});
  let data;try{data=await r.json()}catch{throw Error('Máy chủ trả về dữ liệu không hợp lệ. Vui lòng thử lại.')}
  if(!r.ok){if(r.status===401&&action!=='login'){showLogin();$('loginMessage').textContent='Phiên đăng nhập hết hạn. Đăng nhập lại để tiếp tục lưu nội dung đang soạn.'}throw Error(data.message||'Không thực hiện được thao tác.')}
  return data;
}
async function run(button,fn){if(busy)return;busy=true;const old=button.textContent;const controls=[...document.querySelectorAll('#postForm input,#postForm textarea,#postForm select,#postForm button')].map(el=>[el,el.disabled]);for(const [el]of controls)el.disabled=true;button.disabled=true;button.textContent='Đang xử lý…';try{await fn()}catch(e){tell(e.name==='TimeoutError'?'Kết nối quá lâu. Hãy thử lại.':e.message,true)}finally{for(const[el,disabled]of controls)el.disabled=disabled;button.disabled=false;button.textContent=old;busy=false}}
function showLogin(){$('loginShell').hidden=false;$('adminApp').hidden=true}
async function showApp(email){$('loginShell').hidden=true;$('adminApp').hidden=false;$('account').textContent=email;await load();if(dirty){view(activeView)}else if(current){view('editor')}else view('posts')}
async function load(){const results=await Promise.all([api('posts'),api('content'),fetch('/assets/content-fields.json').then(r=>{if(!r.ok)throw Error('Không tải được cấu hình trang chủ.');return r.json()})]);[posts,content,fields]=results;const mr=await fetch('/assets/members.json');if(!mr.ok)throw Error('Không tải được danh sách thành viên.');memberCatalog=await mr.json();$('memberOwner').replaceChildren(new Option('Thành viên khác (nhập tên bên dưới)',''));for(const m of memberCatalog){const name=content.find(c=>c.id===m.fields.name)?.value||m.name;$('memberOwner').append(new Option(name,m.id))}const selected=$('contentGroup').value;$('contentGroup').replaceChildren(new Option('Tất cả các mục',''));for(const group of new Set(fields.map(f=>f.group||'Nội dung chính')))$('contentGroup').append(new Option(group,group));$('contentGroup').value=selected;renderList();if(activeView==='directory')renderDirectory();if(activeView!=='content'||!dirty)renderContent()}
function leave(){if(busy)return false;return !dirty||confirm('Bạn còn thay đổi chưa lưu. Rời trang soạn thảo?')}
function view(name){activeView=name;for(const v of ['posts','editor','content','directory'])$(v+'View').hidden=v!==name;$('viewTitle').textContent=name==='posts'?(collection==='members'?'Doanh nghiệp thành viên':'Bài viết'):name==='editor'?(collection==='members'?'Hồ sơ doanh nghiệp':'Soạn bài viết'):'Nội dung trang chủ';$('newButton').textContent=collection==='members'?'+ Thêm doanh nghiệp':'+ Thêm bài viết';$('newButton').hidden=name!=='posts';$('postsTab').classList.toggle('active',name!=='content'&&collection==='posts');$('membersTab').classList.toggle('active',name!=='content'&&collection==='members');$('contentTab').classList.toggle('active',name==='content');if(name==='directory'){$('viewTitle').textContent='Thành viên và doanh nghiệp';renderDirectory()}if(name==='posts'&&collection==='members')$('viewTitle').textContent=selectedMember?memberName(selectedMember):'Doanh nghiệp của thành viên khác';$('directoryBack').hidden=collection!=='members';$('totalLabel').textContent=collection==='members'?'Tất cả doanh nghiệp':'Tất cả bài viết';$('searchLabel').textContent=collection==='members'?'Tìm doanh nghiệp':'Tìm bài viết';$('search').placeholder=collection==='members'?'Nhập tên doanh nghiệp…':'Nhập tiêu đề hoặc chuyên mục…';$('filter').options[0].textContent=collection==='members'?'Tất cả doanh nghiệp':'Tất cả bài viết'}
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n}
function renderList(){
  const scoped=posts.filter(p=>collection==='members'?p.category===MEMBER_CATEGORY&&belongsToSelected(p):p.category!==MEMBER_CATEGORY);$('totalCount').textContent=scoped.filter(p=>p.status!=='trash').length;$('publishedCount').textContent=scoped.filter(p=>p.status==='published').length;$('draftCount').textContent=scoped.filter(p=>p.status==='draft').length;
  const term=$('search').value.toLocaleLowerCase('vi'),filter=$('filter').value;
  const list=posts.filter(p=>(collection==='members'?p.category===MEMBER_CATEGORY&&belongsToSelected(p):p.category!==MEMBER_CATEGORY)&&(filter==='all'?p.status!=='trash':p.status===filter)&&(p.title+' '+p.category).toLocaleLowerCase('vi').includes(term));
  $('postList').replaceChildren();if(!list.length){$('postList').append(node('div',term?'Không có bài phù hợp với từ khóa.':filter==='trash'?'Thùng rác đang trống.':collection==='members'?'Chưa có doanh nghiệp. Bấm “Thêm doanh nghiệp” để bắt đầu.':'Chưa có bài viết. Bấm “Thêm bài viết” để bắt đầu.','empty'));return}
  for(const p of list){const row=node('div',undefined,'post-row'),icon=node('div','Lê','post-icon'),info=node('div'),meta=node('div',undefined,'post-meta');if(CMS.imageURL(p.cover_url)){const img=node('img');img.src=CMS.imageURL(p.cover_url);img.alt='';icon.replaceChildren(img)}info.append(node('h3',p.title));meta.append(node('span',p.category),node('span',({draft:'Bản nháp',published:'Đã xuất bản',trash:'Thùng rác'})[p.status],'badge '+p.status),node('span',new Date(p.updated_at).toLocaleDateString('vi-VN')));info.append(meta);const edit=node('button',p.status==='trash'?'Khôi phục':'Chỉnh sửa','secondary');edit.onclick=()=>{if(leave()){dirty=false;openPost(p)}};row.append(icon,info,edit);$('postList').append(row)}
}
function setDirty(){dirty=true;$('saveState').textContent='Có thay đổi chưa lưu'}
function openPost(p=null){current=p?structuredClone(p):null;cover=p?.cover_url||'';const profile=p?.body?.find(b=>b.type==='profile')||{};blocks=structuredClone(p?.body?.filter(b=>b.type!=='profile')||[{type:'p',text:''}]);const isMember=collection==='members';$('memberOwner').value=profile.member_id||memberCatalog.find(m=>CMS.slug(profile.representative||'')===m.id)?.id||'';$('profileFields').hidden=!isMember;$('backButton').textContent=isMember?'← Danh sách doanh nghiệp':'← Danh sách bài viết';$('postTitle').placeholder=isMember?'Nhập tên doanh nghiệp':'Nhập tiêu đề bài viết';$('excerpt').placeholder=isMember?'Giới thiệu ngắn trên thẻ doanh nghiệp':'Giới thiệu ngắn hiển thị trên danh sách tin';$('titleLabel').textContent=isMember?'Tên doanh nghiệp':'Tiêu đề bài viết';$('coverLabel').textContent=isMember?'Ảnh đại diện / logo doanh nghiệp':'Ảnh bìa';for(const [id,key] of [['representative','representative'],['sector','sector'],['businessPhone','phone'],['businessAddress','address'],['businessWebsite','website']])$(id).value=profile[key]||'';$('postTitle').value=p?.title||'';$('slug').value=p?.slug||'';$('excerpt').value=p?.excerpt||'';$('category').value=p?.category||(isMember?MEMBER_CATEGORY:CMS.categories[0]);$('category').disabled=isMember;for(const option of $('category').options)option.disabled=!isMember&&option.value===MEMBER_CATEGORY;$('publishedDate').value=p?.published_at?new Date(p.published_at).toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'}):new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Bangkok'});$('saveState').textContent=p?'Đã lưu: '+new Date(p.updated_at).toLocaleString('vi-VN'):'Bài mới · Chưa lưu';$('trashButton').hidden=!p||p.status==='trash';$('publishButton').textContent=p?.status==='published'?'Cập nhật bài viết':'Xuất bản';$('draftButton').textContent=p?.status==='trash'?'Khôi phục vào bản nháp':'Lưu bản nháp';$('coverFile').value='';renderCover();renderBlocks();view('editor');tell(p?.status==='trash'?'Bài đang trong thùng rác. Lưu bản nháp để khôi phục.':'');dirty=false}
function renderCover(){const url=CMS.imageURL(cover);$('coverPreview').hidden=!url;$('removeCover').hidden=!url;if(url)$('coverPreview').src=url;else $('coverPreview').removeAttribute('src')}
async function upload(file){if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3*1024*1024)throw Error('Chọn ảnh JPG, PNG hoặc WEBP tối đa 3 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(Error('Không đọc được ảnh.'));r.readAsDataURL(file)});return (await api('upload',{type:file.type,data})).url}
function renderBlocks(){
  $('blocks').replaceChildren();$('blockCount').textContent=blocks.length+' đoạn';
  blocks.forEach((b,i)=>{const wrap=node('div',undefined,'block'),tools=node('div',undefined,'block-tools');tools.append(node('strong',`${i+1}. ${b.type==='img'?'Hình ảnh':b.type==='h2'?'Tiêu đề mục':b.type==='link'?'Liên kết website':'Đoạn văn'}`));
    for(const [label,fn,disabled] of [['↑',()=>{[blocks[i-1],blocks[i]]=[blocks[i],blocks[i-1]]},i===0],['↓',()=>{[blocks[i+1],blocks[i]]=[blocks[i],blocks[i+1]]},i===blocks.length-1],['Bỏ',()=>{if(confirm('Bỏ đoạn nội dung này?'))blocks.splice(i,1)},false]]){const bt=node('button',label);bt.type='button';bt.disabled=disabled;bt.setAttribute('aria-label',label==='↑'?'Đưa đoạn lên':label==='↓'?'Đưa đoạn xuống':'Bỏ đoạn');bt.onclick=()=>{if(busy)return;fn();setDirty();renderBlocks()};tools.append(bt)}wrap.append(tools);
    if(b.type==='img'){if(CMS.imageURL(b.src)){const img=node('img');img.src=CMS.imageURL(b.src);img.alt=b.caption||'';wrap.append(img)}const label=node('label','Chú thích ảnh'),input=node('input');input.value=b.caption||'';input.maxLength=500;input.oninput=()=>{b.caption=input.value;setDirty()};label.append(input);wrap.append(label);const replace=node('label','Tải ảnh lên'),file=node('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.onchange=async()=>{if(busy)return;busy=true;file.disabled=true;try{b.src=await upload(file.files[0]);setDirty();renderBlocks()}catch(e){tell(e.message,true)}finally{busy=false;file.disabled=false}};replace.append(file);wrap.append(replace)}
    else if(b.type==='link'){for(const [key,label]of [['text','Tên liên kết'],['href','Địa chỉ website (https://…)']]){const l=node('label',label),input=node('input');input.value=b[key]||'';input.oninput=()=>{b[key]=input.value;setDirty()};l.append(input);wrap.append(l)}}
    else{const text=node('textarea');text.rows=b.type==='h2'?2:5;text.value=b.text||'';text.maxLength=20000;text.setAttribute('aria-label',b.type==='h2'?'Nội dung tiêu đề mục':'Nội dung đoạn văn');text.oninput=()=>{b.text=text.value;setDirty()};wrap.append(text)}$('blocks').append(wrap)
  });
}
function values(status){if(collection==='members'&&!$('representative').value.trim())throw Error('Chọn thành viên hoặc nhập tên thành viên đại diện.');return CMS.validatePost({title:$('postTitle').value,slug:$('slug').value,excerpt:$('excerpt').value,category:$('category').value,cover_url:cover,body:collection==='members'?[{type:'profile',member_id:$('memberOwner').value||CMS.slug($('representative').value),representative:$('representative').value,sector:$('sector').value,phone:$('businessPhone').value,address:$('businessAddress').value,website:$('businessWebsite').value},...blocks]:blocks,status,published_at:$('publishedDate').value?new Date($('publishedDate').value+'T00:00:00+07:00').toISOString():null})}
async function save(status){
  if(status==='published'&&!confirm(current?.status==='published'?'Cập nhật nội dung bài đang công khai trên website?':'Xuất bản bài này để mọi người đọc trên website?'))return;
  const p=values(status);if(current){p.id=current.id;p.updated_at=current.updated_at}const saved=await api('save-post',p);const i=posts.findIndex(x=>x.id===saved.id);if(i<0)posts.unshift(saved);else posts[i]=saved;dirty=false;openPost(saved);renderList();tell(status==='published'?'Đã xuất bản. Bài viết đã được lưu vào cơ sở dữ liệu.':status==='trash'?'Đã chuyển vào thùng rác. Có thể khôi phục từ danh sách bài viết.':'Đã lưu bản nháp. Chỉ quản trị viên xem được.');if(status==='trash')view('posts')
}
function renderContent(){
  $('contentFields').replaceChildren();contentDirty.clear();
  for(const f of fields){if($('contentGroup').value&&($('contentGroup').value!==(f.group||'Nội dung chính')))continue;const record=content.find(c=>c.id===f.id);const panel=node('div',undefined,'panel'),label=node('label',f.label),input=node('textarea');input.rows=f.rows||3;input.maxLength=10000;input.value=record?.value??f.default;label.append(input);const button=node('button','Lưu mục này','primary');button.type='button';button.disabled=!record;button.onclick=()=>run(button,async()=>{if(!confirm('Lưu và hiển thị nội dung mục này trên trang chủ?'))return;input.disabled=true;try{const saved=await api('save-content',{id:f.id,value:input.value,updated_at:record.updated_at});Object.assign(record,saved);contentDirty.delete(f.id);dirty=contentDirty.size>0;tell('Đã cập nhật: '+f.label)}finally{input.disabled=false}});input.oninput=()=>{contentDirty.add(f.id);dirty=true};if(['image','src'].includes(f.kind)){input.rows=2;input.placeholder='Đường dẫn ảnh hoặc tải ảnh lên';const file=node('input');file.type='file';file.accept='image/jpeg,image/png,image/webp';file.onchange=()=>run(button,async()=>{input.value=await upload(file.files[0]);contentDirty.add(f.id);dirty=true;tell('Đã tải ảnh. Bấm Lưu mục này để hiển thị.');});label.append(file)}panel.append(label,button);if(!record)panel.append(node('p','Mục này chưa được khởi tạo trong cơ sở dữ liệu.','hint'));$('contentFields').append(panel)}
}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('loginButton').disabled=true;$('loginMessage').textContent='Đang đăng nhập…';try{const s=await api('login',{email:$('email').value.trim(),password:$('password').value});$('password').value='';$('loginMessage').textContent='';await showApp(s.email)}catch(e){$('loginMessage').textContent=e.message;tell(e.message,true)}finally{busy=false;$('loginButton').disabled=false}};
$('membersTab').onclick=()=>{if(leave()){collection='members';selectedMember=null;dirty=false;current=null;view('directory')}};
$('postsTab').onclick=()=>{if(leave()){collection='posts';dirty=false;view('posts');renderList()}};$('contentTab').onclick=()=>{if(leave()){dirty=false;view('content');renderContent()}};$('backButton').onclick=()=>{if(leave()){dirty=false;current=null;view('posts')}};$('newButton').onclick=()=>{if(leave()){openPost();if(collection==='members'&&selectedMember){$('memberOwner').value=selectedMember;$('representative').value=memberName(selectedMember)}}};
$('contentGroup').onchange=()=>{if(leave()){dirty=false;renderContent()}};
$('search').oninput=renderList;$('filter').onchange=renderList;$('reloadButton').onclick=()=>run($('reloadButton'),load);
$('postTitle').oninput=()=>{if(!current){$('slug').value=CMS.slug($('postTitle').value)}setDirty()};for(const id of ['slug','excerpt','category','publishedDate'])$(id).oninput=setDirty;
$('memberOwner').onchange=()=>{const m=memberCatalog.find(m=>m.id===$('memberOwner').value);if(m)$('representative').value=content.find(c=>c.id===m.fields.name)?.value||m.name;setDirty()};
$('addLink').onclick=()=>{if(busy)return;blocks.push({type:'link',text:'',href:''});setDirty();renderBlocks()};
for(const id of ['representative','sector','businessPhone','businessAddress','businessWebsite'])$(id).oninput=setDirty;
$('addParagraph').onclick=()=>{if(busy)return;blocks.push({type:'p',text:''});setDirty();renderBlocks()};$('addHeading').onclick=()=>{if(busy)return;blocks.push({type:'h2',text:''});setDirty();renderBlocks()};$('addImage').onclick=()=>{if(busy)return;blocks.push({type:'img',src:'',caption:''});setDirty();renderBlocks()};
$('coverFile').onchange=async()=>{if(busy)return;busy=true;$('coverFile').disabled=true;try{cover=await upload($('coverFile').files[0]);setDirty();renderCover()}catch(e){tell(e.message,true)}finally{busy=false;$('coverFile').disabled=false}};$('removeCover').onclick=()=>{cover='';setDirty();renderCover()};
$('postForm').onsubmit=e=>{e.preventDefault();const button=e.submitter||$('draftButton');run(button,()=>save(button.value||'draft'))};$('trashButton').onclick=()=>{if(confirm('Chuyển bài này vào thùng rác? Bài sẽ được gỡ khỏi website và có thể khôi phục.'))run($('trashButton'),()=>save('trash'))};
$('previewButton').onclick=()=>{try{const p=values('draft');$('previewTitle').textContent=p.title;$('previewCategory').textContent=p.category;$('previewExcerpt').textContent=p.excerpt;$('previewCover').hidden=!p.cover_url;if(p.cover_url)$('previewCover').src=p.cover_url;else $('previewCover').removeAttribute('src');CMS.renderBody($('previewBody'),p.body);$('previewDialog').showModal()}catch(e){tell(e.message,true)}};$('closePreview').onclick=()=>$('previewDialog').close();
$('logoutButton').onclick=()=>{if(leave())run($('logoutButton'),async()=>{await api('logout',{});posts=[];content=[];current=null;blocks=[];cover='';dirty=false;$('postForm').reset();$('blocks').replaceChildren();$('postList').replaceChildren();$('contentFields').replaceChildren();showLogin()})};
$('backupButton').onclick=()=>run($('backupButton'),async()=>{const [p,c]=await Promise.all([api('posts'),api('content')]);const blob=new Blob([JSON.stringify({version:1,exported_at:new Date().toISOString(),posts:p,content:c},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='ldbc-sao-luu-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);tell('Đã tải bản sao bài viết và nội dung. Ảnh được lưu bằng đường dẫn trong bản sao này.')});
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}});
for(const category of CMS.categories){const option=node('option',category);option.value=category;$('category').append(option)}
(async()=>{try{const h=await api('health');$('setup').hidden=h.configured;$('loginButton').disabled=!h.configured;if(!h.configured)return;try{const s=await api('session');await showApp(s.email)}catch(e){$('loginMessage').textContent=e.message}}catch(e){$('loginMessage').textContent='Không kiểm tra được kết nối: '+e.message}})();

function memberName(id){const m=memberCatalog.find(m=>m.id===id);return content.find(c=>c.id===m?.fields.name)?.value||m?.name||id}
function belongsToSelected(p){const key=CMS.memberKey(p);return selectedMember?key===selectedMember:!memberCatalog.some(m=>m.id===key)}
function renderDirectory(){
  $('memberDirectory').replaceChildren();
  for(const m of memberCatalog){
    const button=node('button',undefined,'member-directory-card'),avatar=node('div',m.initials,'member-directory-avatar'),info=node('div',undefined,'member-directory-info');
    const photo=CMS.imageURL(content.find(c=>c.id===m.fields.avatar)?.value||'');if(photo){const img=node('img');img.src=photo;img.alt='';avatar.replaceChildren(img)}
    const count=posts.filter(p=>p.category===MEMBER_CATEGORY&&p.status!=='trash'&&CMS.memberKey(p)===m.id).length;
    info.append(node('strong',memberName(m.id)),node('small',content.find(c=>c.id===m.fields.role)?.value||m.role),node('span',count+' doanh nghiệp'),node('span','Quản lý doanh nghiệp →'));button.append(avatar,info);
    button.onclick=()=>{if(!leave())return;dirty=false;selectedMember=m.id;current=null;$('search').value='';$('filter').value='all';view('posts');renderList()};$('memberDirectory').append(button);
  }
}
$('directoryBack').onclick=()=>{if(leave()){dirty=false;current=null;view('directory')}};
$('otherMembersButton').onclick=()=>{selectedMember=null;$('search').value='';$('filter').value='all';view('posts');renderList()};
